apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  namespace: edu-sleepy-engelbart
  labels:
    app.kubernetes.io/app: django-app
    app.kubernetes.io/name: django
    app.kubernetes.io/env: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      name: django
      labels:
        app: django
    spec:
      containers:
        - name: django
          image: alexnv/k8s-dvmn:lastest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: postgres
            - secretRef:
                name: django-secret
          volumeMounts:
            - name: pg-root-cert
              mountPath: "/opt/.postgresql"
              readOnly: true
          #ports:
          #  - containerPort: 80
          #    name: http
          resources:
            limits:
              cpu: "250m"
              memory: "128Mi"
            requests:
              cpu: "100m"
              memory: "64Mi"
      volumes:
        - name: pg-root-cert
          secret:
            secretName: pg-root-cert