apiVersion: v1
kind: Secret
metadata:
  name: django-secret
  namespace: edu-sleepy-engelbart
  labels:
    app.kubernetes.io/name: django-secret
    app.kubernetes.io/env: dev
type: Opaque
stringData:
  SECRET_KEY: "secret"
  ALLOWED_HOSTS: "localhost"
  DEBUG: "False"
  DATABASE_URL: "postgres://$(username):$(password)@$(host):$(port)/$(name)?sslmode=verify-full&sslrootcert=/opt/.postgresql/root.crt"