apiVersion: v1
kind: Secret
metadata:
  name: postgress-secret
  namespace: edu-sleepy-engelbart
  labels:
    app.kubernetes.io/name: postgress-secret
    app.kubernetes.io/env: dev
type: Opaque
stringData:
  username: ""
  password: ""
  host: ""
  port: ""
  name: ""
