apiVersion: v1
kind: Service
metadata:
  name: django-service
  namespace: edu-sleepy-engelbart
  labels:
    app.kubernetes.io/name: django-service
    app.kubernetes.io/env: dev
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30031
  selector:
    app: django
  type: NodePort