apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: edu-sleepy-engelbart
  labels:
    environment: production
    app: nginx
    app.kubernetes.io/name: nginx
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  annotations: {}
  name: nginx-service
  namespace: edu-sleepy-engelbart
spec:
  ports:
  - nodePort: 30031
    port: 81
    targetPort: 80
    protocol: "TCP"
  selector:
    app.kubernetes.io/name: nginx
  type: NodePort